stages:
- name: compile
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: flask-file-list-upload:${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      registry: core.harbor.domain
    env:
      PLUGIN_DEBUG: "true"  
- name: deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
    envFrom:
    - sourceName: registry-crt
      sourceKey: ca.crt
    - sourceName: registry-crt
      sourceKey: client.cert
    - sourceName: registry-crt
      sourceKey: client.key
timeout: 60
