stages:
- name: compile
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: flask-file-list-upload:${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      registry: 192.168.143.79:30002
- name: deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 60
