stages:
- name: compile
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: test/flask-file-list-upload:${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      registry: core.harbor.domain
      PLUGIN_INSECURE: true
- name: deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 60
