stages:
- name: compile
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: test/flask-file-list-upload:${CICD_EXECUTION_SEQUENCE}
      registry: core.harbor.domain
- name: deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
    envFrom:
    - sourceName: registry-crt
      sourceKey: ca.crt
timeout: 60
