stages:
- name: compile
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: flask-file-list-upload:${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      registry: core.harbor.domain
    env:
      PLUGIN_DEBUG: "true"
- name: deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
    envFrom:
    - sourceName: harbor-ca
      sourceKey: ca.crt
timeout: 60
