stages:
- name: compile
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: example/app:v1
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 60
