apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: flask-file-list-upload
  selfLink: /apis/apps/v1beta2/namespaces/default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-default-flask-file-list-upload
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        cattle.io/timestamp: 2019-02-28T13:12:15Z        
      labels:
        workload.user.cattle.io/workloadselector: deployment-default-flask-file-list-upload
    spec:
      containers:
      - env:
        - name: LISTEN_PORT
          value: "8080"
        - name: NGINX_MAX_UPLOAD
          value: 100m
        image: ${CICD_IMAGE}:${CICD_EXECUTION_SEQUENCE}
        imagePullPolicy: Always
        name: uwsgi-nginx-flask
        ports:
        - containerPort: 8080
          hostPort: 8080
          name: 8080tcp80800
          protocol: TCP
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: {}
          privileged: false
          procMount: Default
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30

